CONFIG_ESP_SERIAL_FLASHER=y
#CONFIG_ESP_SERIAL_FLASHER_LOG_LEVEL_DBG=y

CONFIG_LOG=y
CONFIG_LOG_BACKEND_SHOW_COLOR=y
CONFIG_LOG_DEFAULT_LEVEL=2

CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_CONSOLE_GETCHAR=y
