/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Vendored from ESP-IDF components/efuse — adapted and regenerated by tools/copy_efuse_headers.py. */
#include "esp_loader_efuse.h"
#include "efuse/esp32c3/esp_loader_efuse_table.h"

// md5_digest_table f41d6027e08973065c84a93ebd369dee
// This file was generated from the file esp_efuse_table.csv. DO NOT CHANGE THIS FILE MANUALLY.
// If you want to change some fields, you need to change esp_efuse_table.csv file
// then run `efuse_common_table` or `efuse_custom_table` command it will generate this file.
// To show efuse_table run the command 'show_efuse_table'.

static const esp_loader_efuse_desc_t WR_DIS[] = {
    {0, 0, 32}, 	 // [] Disable programming of individual eFuses,
};

static const esp_loader_efuse_desc_t WR_DIS_RD_DIS[] = {
    {0, 0, 1}, 	 // [] wr_dis of RD_DIS,
};

static const esp_loader_efuse_desc_t WR_DIS_DIS_ICACHE[] = {
    {0, 2, 1}, 	 // [] wr_dis of DIS_ICACHE,
};

static const esp_loader_efuse_desc_t WR_DIS_DIS_USB_JTAG[] = {
    {0, 2, 1}, 	 // [] wr_dis of DIS_USB_JTAG,
};

static const esp_loader_efuse_desc_t WR_DIS_DIS_DOWNLOAD_ICACHE[] = {
    {0, 2, 1}, 	 // [] wr_dis of DIS_DOWNLOAD_ICACHE,
};

static const esp_loader_efuse_desc_t WR_DIS_DIS_USB_SERIAL_JTAG[] = {
    {0, 2, 1}, 	 // [WR_DIS.DIS_USB_DEVICE] wr_dis of DIS_USB_SERIAL_JTAG,
};

static const esp_loader_efuse_desc_t WR_DIS_DIS_FORCE_DOWNLOAD[] = {
    {0, 2, 1}, 	 // [] wr_dis of DIS_FORCE_DOWNLOAD,
};

static const esp_loader_efuse_desc_t WR_DIS_DIS_TWAI[] = {
    {0, 2, 1}, 	 // [WR_DIS.DIS_CAN] wr_dis of DIS_TWAI,
};

static const esp_loader_efuse_desc_t WR_DIS_JTAG_SEL_ENABLE[] = {
    {0, 2, 1}, 	 // [] wr_dis of JTAG_SEL_ENABLE,
};

static const esp_loader_efuse_desc_t WR_DIS_DIS_PAD_JTAG[] = {
    {0, 2, 1}, 	 // [] wr_dis of DIS_PAD_JTAG,
};

static const esp_loader_efuse_desc_t WR_DIS_DIS_DOWNLOAD_MANUAL_ENCRYPT[] = {
    {0, 2, 1}, 	 // [] wr_dis of DIS_DOWNLOAD_MANUAL_ENCRYPT,
};

static const esp_loader_efuse_desc_t WR_DIS_WDT_DELAY_SEL[] = {
    {0, 3, 1}, 	 // [] wr_dis of WDT_DELAY_SEL,
};

static const esp_loader_efuse_desc_t WR_DIS_SPI_BOOT_CRYPT_CNT[] = {
    {0, 4, 1}, 	 // [] wr_dis of SPI_BOOT_CRYPT_CNT,
};

static const esp_loader_efuse_desc_t WR_DIS_SECURE_BOOT_KEY_REVOKE0[] = {
    {0, 5, 1}, 	 // [] wr_dis of SECURE_BOOT_KEY_REVOKE0,
};

static const esp_loader_efuse_desc_t WR_DIS_SECURE_BOOT_KEY_REVOKE1[] = {
    {0, 6, 1}, 	 // [] wr_dis of SECURE_BOOT_KEY_REVOKE1,
};

static const esp_loader_efuse_desc_t WR_DIS_SECURE_BOOT_KEY_REVOKE2[] = {
    {0, 7, 1}, 	 // [] wr_dis of SECURE_BOOT_KEY_REVOKE2,
};

static const esp_loader_efuse_desc_t WR_DIS_KEY_PURPOSE_0[] = {
    {0, 8, 1}, 	 // [WR_DIS.KEY0_PURPOSE] wr_dis of KEY_PURPOSE_0,
};

static const esp_loader_efuse_desc_t WR_DIS_KEY_PURPOSE_1[] = {
    {0, 9, 1}, 	 // [WR_DIS.KEY1_PURPOSE] wr_dis of KEY_PURPOSE_1,
};

static const esp_loader_efuse_desc_t WR_DIS_KEY_PURPOSE_2[] = {
    {0, 10, 1}, 	 // [WR_DIS.KEY2_PURPOSE] wr_dis of KEY_PURPOSE_2,
};

static const esp_loader_efuse_desc_t WR_DIS_KEY_PURPOSE_3[] = {
    {0, 11, 1}, 	 // [WR_DIS.KEY3_PURPOSE] wr_dis of KEY_PURPOSE_3,
};

static const esp_loader_efuse_desc_t WR_DIS_KEY_PURPOSE_4[] = {
    {0, 12, 1}, 	 // [WR_DIS.KEY4_PURPOSE] wr_dis of KEY_PURPOSE_4,
};

static const esp_loader_efuse_desc_t WR_DIS_KEY_PURPOSE_5[] = {
    {0, 13, 1}, 	 // [WR_DIS.KEY5_PURPOSE] wr_dis of KEY_PURPOSE_5,
};

static const esp_loader_efuse_desc_t WR_DIS_SECURE_BOOT_EN[] = {
    {0, 15, 1}, 	 // [] wr_dis of SECURE_BOOT_EN,
};

static const esp_loader_efuse_desc_t WR_DIS_SECURE_BOOT_AGGRESSIVE_REVOKE[] = {
    {0, 16, 1}, 	 // [] wr_dis of SECURE_BOOT_AGGRESSIVE_REVOKE,
};

static const esp_loader_efuse_desc_t WR_DIS_FLASH_TPUW[] = {
    {0, 18, 1}, 	 // [] wr_dis of FLASH_TPUW,
};

static const esp_loader_efuse_desc_t WR_DIS_DIS_DOWNLOAD_MODE[] = {
    {0, 18, 1}, 	 // [] wr_dis of DIS_DOWNLOAD_MODE,
};

static const esp_loader_efuse_desc_t WR_DIS_DIS_DIRECT_BOOT[] = {
    {0, 18, 1}, 	 // [WR_DIS.DIS_LEGACY_SPI_BOOT] wr_dis of DIS_DIRECT_BOOT,
};

static const esp_loader_efuse_desc_t WR_DIS_DIS_USB_SERIAL_JTAG_ROM_PRINT[] = {
    {0, 18, 1}, 	 // [WR_DIS.UART_PRINT_CHANNEL] wr_dis of DIS_USB_SERIAL_JTAG_ROM_PRINT,
};

static const esp_loader_efuse_desc_t WR_DIS_DIS_USB_SERIAL_JTAG_DOWNLOAD_MODE[] = {
    {0, 18, 1}, 	 // [WR_DIS.DIS_USB_DOWNLOAD_MODE] wr_dis of DIS_USB_SERIAL_JTAG_DOWNLOAD_MODE,
};

static const esp_loader_efuse_desc_t WR_DIS_ENABLE_SECURITY_DOWNLOAD[] = {
    {0, 18, 1}, 	 // [] wr_dis of ENABLE_SECURITY_DOWNLOAD,
};

static const esp_loader_efuse_desc_t WR_DIS_UART_PRINT_CONTROL[] = {
    {0, 18, 1}, 	 // [] wr_dis of UART_PRINT_CONTROL,
};

static const esp_loader_efuse_desc_t WR_DIS_FORCE_SEND_RESUME[] = {
    {0, 18, 1}, 	 // [] wr_dis of FORCE_SEND_RESUME,
};

static const esp_loader_efuse_desc_t WR_DIS_SECURE_VERSION[] = {
    {0, 18, 1}, 	 // [] wr_dis of SECURE_VERSION,
};

static const esp_loader_efuse_desc_t WR_DIS_ERR_RST_ENABLE[] = {
    {0, 19, 1}, 	 // [] wr_dis of ERR_RST_ENABLE,
};

static const esp_loader_efuse_desc_t WR_DIS_DISABLE_WAFER_VERSION_MAJOR[] = {
    {0, 19, 1}, 	 // [] wr_dis of DISABLE_WAFER_VERSION_MAJOR,
};

static const esp_loader_efuse_desc_t WR_DIS_DISABLE_BLK_VERSION_MAJOR[] = {
    {0, 19, 1}, 	 // [] wr_dis of DISABLE_BLK_VERSION_MAJOR,
};

static const esp_loader_efuse_desc_t WR_DIS_BLK1[] = {
    {0, 20, 1}, 	 // [] wr_dis of BLOCK1,
};

static const esp_loader_efuse_desc_t WR_DIS_MAC[] = {
    {0, 20, 1}, 	 // [WR_DIS.MAC_FACTORY] wr_dis of MAC,
};

static const esp_loader_efuse_desc_t WR_DIS_SPI_PAD_CONFIG_CLK[] = {
    {0, 20, 1}, 	 // [] wr_dis of SPI_PAD_CONFIG_CLK,
};

static const esp_loader_efuse_desc_t WR_DIS_SPI_PAD_CONFIG_Q[] = {
    {0, 20, 1}, 	 // [] wr_dis of SPI_PAD_CONFIG_Q,
};

static const esp_loader_efuse_desc_t WR_DIS_SPI_PAD_CONFIG_D[] = {
    {0, 20, 1}, 	 // [] wr_dis of SPI_PAD_CONFIG_D,
};

static const esp_loader_efuse_desc_t WR_DIS_SPI_PAD_CONFIG_CS[] = {
    {0, 20, 1}, 	 // [] wr_dis of SPI_PAD_CONFIG_CS,
};

static const esp_loader_efuse_desc_t WR_DIS_SPI_PAD_CONFIG_HD[] = {
    {0, 20, 1}, 	 // [] wr_dis of SPI_PAD_CONFIG_HD,
};

static const esp_loader_efuse_desc_t WR_DIS_SPI_PAD_CONFIG_WP[] = {
    {0, 20, 1}, 	 // [] wr_dis of SPI_PAD_CONFIG_WP,
};

static const esp_loader_efuse_desc_t WR_DIS_SPI_PAD_CONFIG_DQS[] = {
    {0, 20, 1}, 	 // [] wr_dis of SPI_PAD_CONFIG_DQS,
};

static const esp_loader_efuse_desc_t WR_DIS_SPI_PAD_CONFIG_D4[] = {
    {0, 20, 1}, 	 // [] wr_dis of SPI_PAD_CONFIG_D4,
};

static const esp_loader_efuse_desc_t WR_DIS_SPI_PAD_CONFIG_D5[] = {
    {0, 20, 1}, 	 // [] wr_dis of SPI_PAD_CONFIG_D5,
};

static const esp_loader_efuse_desc_t WR_DIS_SPI_PAD_CONFIG_D6[] = {
    {0, 20, 1}, 	 // [] wr_dis of SPI_PAD_CONFIG_D6,
};

static const esp_loader_efuse_desc_t WR_DIS_SPI_PAD_CONFIG_D7[] = {
    {0, 20, 1}, 	 // [] wr_dis of SPI_PAD_CONFIG_D7,
};

static const esp_loader_efuse_desc_t WR_DIS_WAFER_VERSION_MINOR_LO[] = {
    {0, 20, 1}, 	 // [] wr_dis of WAFER_VERSION_MINOR_LO,
};

static const esp_loader_efuse_desc_t WR_DIS_PKG_VERSION[] = {
    {0, 20, 1}, 	 // [] wr_dis of PKG_VERSION,
};

static const esp_loader_efuse_desc_t WR_DIS_BLK_VERSION_MINOR[] = {
    {0, 20, 1}, 	 // [] wr_dis of BLK_VERSION_MINOR,
};

static const esp_loader_efuse_desc_t WR_DIS_FLASH_CAP[] = {
    {0, 20, 1}, 	 // [] wr_dis of FLASH_CAP,
};

static const esp_loader_efuse_desc_t WR_DIS_FLASH_TEMP[] = {
    {0, 20, 1}, 	 // [] wr_dis of FLASH_TEMP,
};

static const esp_loader_efuse_desc_t WR_DIS_FLASH_VENDOR[] = {
    {0, 20, 1}, 	 // [] wr_dis of FLASH_VENDOR,
};

static const esp_loader_efuse_desc_t WR_DIS_K_RTC_LDO[] = {
    {0, 20, 1}, 	 // [] wr_dis of K_RTC_LDO,
};

static const esp_loader_efuse_desc_t WR_DIS_K_DIG_LDO[] = {
    {0, 20, 1}, 	 // [] wr_dis of K_DIG_LDO,
};

static const esp_loader_efuse_desc_t WR_DIS_V_RTC_DBIAS20[] = {
    {0, 20, 1}, 	 // [] wr_dis of V_RTC_DBIAS20,
};

static const esp_loader_efuse_desc_t WR_DIS_V_DIG_DBIAS20[] = {
    {0, 20, 1}, 	 // [] wr_dis of V_DIG_DBIAS20,
};

static const esp_loader_efuse_desc_t WR_DIS_DIG_DBIAS_HVT[] = {
    {0, 20, 1}, 	 // [] wr_dis of DIG_DBIAS_HVT,
};

static const esp_loader_efuse_desc_t WR_DIS_THRES_HVT[] = {
    {0, 20, 1}, 	 // [] wr_dis of THRES_HVT,
};

static const esp_loader_efuse_desc_t WR_DIS_WAFER_VERSION_MINOR_HI[] = {
    {0, 20, 1}, 	 // [] wr_dis of WAFER_VERSION_MINOR_HI,
};

static const esp_loader_efuse_desc_t WR_DIS_WAFER_VERSION_MAJOR[] = {
    {0, 20, 1}, 	 // [] wr_dis of WAFER_VERSION_MAJOR,
};

static const esp_loader_efuse_desc_t WR_DIS_SYS_DATA_PART1[] = {
    {0, 21, 1}, 	 // [] wr_dis of BLOCK2,
};

static const esp_loader_efuse_desc_t WR_DIS_OPTIONAL_UNIQUE_ID[] = {
    {0, 21, 1}, 	 // [] wr_dis of OPTIONAL_UNIQUE_ID,
};

static const esp_loader_efuse_desc_t WR_DIS_BLK_VERSION_MAJOR[] = {
    {0, 21, 1}, 	 // [] wr_dis of BLK_VERSION_MAJOR,
};

static const esp_loader_efuse_desc_t WR_DIS_TEMP_CALIB[] = {
    {0, 21, 1}, 	 // [] wr_dis of TEMP_CALIB,
};

static const esp_loader_efuse_desc_t WR_DIS_OCODE[] = {
    {0, 21, 1}, 	 // [] wr_dis of OCODE,
};

static const esp_loader_efuse_desc_t WR_DIS_ADC1_INIT_CODE_ATTEN0[] = {
    {0, 21, 1}, 	 // [] wr_dis of ADC1_INIT_CODE_ATTEN0,
};

static const esp_loader_efuse_desc_t WR_DIS_ADC1_INIT_CODE_ATTEN1[] = {
    {0, 21, 1}, 	 // [] wr_dis of ADC1_INIT_CODE_ATTEN1,
};

static const esp_loader_efuse_desc_t WR_DIS_ADC1_INIT_CODE_ATTEN2[] = {
    {0, 21, 1}, 	 // [] wr_dis of ADC1_INIT_CODE_ATTEN2,
};

static const esp_loader_efuse_desc_t WR_DIS_ADC1_INIT_CODE_ATTEN3[] = {
    {0, 21, 1}, 	 // [] wr_dis of ADC1_INIT_CODE_ATTEN3,
};

static const esp_loader_efuse_desc_t WR_DIS_ADC1_CAL_VOL_ATTEN0[] = {
    {0, 21, 1}, 	 // [] wr_dis of ADC1_CAL_VOL_ATTEN0,
};

static const esp_loader_efuse_desc_t WR_DIS_ADC1_CAL_VOL_ATTEN1[] = {
    {0, 21, 1}, 	 // [] wr_dis of ADC1_CAL_VOL_ATTEN1,
};

static const esp_loader_efuse_desc_t WR_DIS_ADC1_CAL_VOL_ATTEN2[] = {
    {0, 21, 1}, 	 // [] wr_dis of ADC1_CAL_VOL_ATTEN2,
};

static const esp_loader_efuse_desc_t WR_DIS_ADC1_CAL_VOL_ATTEN3[] = {
    {0, 21, 1}, 	 // [] wr_dis of ADC1_CAL_VOL_ATTEN3,
};

static const esp_loader_efuse_desc_t WR_DIS_BLOCK_USR_DATA[] = {
    {0, 22, 1}, 	 // [WR_DIS.USER_DATA] wr_dis of BLOCK_USR_DATA,
};

static const esp_loader_efuse_desc_t WR_DIS_CUSTOM_MAC[] = {
    {0, 22, 1}, 	 // [WR_DIS.MAC_CUSTOM WR_DIS.USER_DATA_MAC_CUSTOM] wr_dis of CUSTOM_MAC,
};

static const esp_loader_efuse_desc_t WR_DIS_BLOCK_KEY0[] = {
    {0, 23, 1}, 	 // [WR_DIS.KEY0] wr_dis of BLOCK_KEY0,
};

static const esp_loader_efuse_desc_t WR_DIS_BLOCK_KEY1[] = {
    {0, 24, 1}, 	 // [WR_DIS.KEY1] wr_dis of BLOCK_KEY1,
};

static const esp_loader_efuse_desc_t WR_DIS_BLOCK_KEY2[] = {
    {0, 25, 1}, 	 // [WR_DIS.KEY2] wr_dis of BLOCK_KEY2,
};

static const esp_loader_efuse_desc_t WR_DIS_BLOCK_KEY3[] = {
    {0, 26, 1}, 	 // [WR_DIS.KEY3] wr_dis of BLOCK_KEY3,
};

static const esp_loader_efuse_desc_t WR_DIS_BLOCK_KEY4[] = {
    {0, 27, 1}, 	 // [WR_DIS.KEY4] wr_dis of BLOCK_KEY4,
};

static const esp_loader_efuse_desc_t WR_DIS_BLOCK_KEY5[] = {
    {0, 28, 1}, 	 // [WR_DIS.KEY5] wr_dis of BLOCK_KEY5,
};

static const esp_loader_efuse_desc_t WR_DIS_BLOCK_SYS_DATA2[] = {
    {0, 29, 1}, 	 // [WR_DIS.SYS_DATA_PART2] wr_dis of BLOCK_SYS_DATA2,
};

static const esp_loader_efuse_desc_t WR_DIS_USB_EXCHG_PINS[] = {
    {0, 30, 1}, 	 // [] wr_dis of USB_EXCHG_PINS,
};

static const esp_loader_efuse_desc_t WR_DIS_VDD_SPI_AS_GPIO[] = {
    {0, 30, 1}, 	 // [] wr_dis of VDD_SPI_AS_GPIO,
};

static const esp_loader_efuse_desc_t WR_DIS_SOFT_DIS_JTAG[] = {
    {0, 31, 1}, 	 // [] wr_dis of SOFT_DIS_JTAG,
};

static const esp_loader_efuse_desc_t RD_DIS[] = {
    {0, 32, 7}, 	 // [] Disable reading from BlOCK4-10,
};

static const esp_loader_efuse_desc_t RD_DIS_BLOCK_KEY0[] = {
    {0, 32, 1}, 	 // [RD_DIS.KEY0] rd_dis of BLOCK_KEY0,
};

static const esp_loader_efuse_desc_t RD_DIS_BLOCK_KEY1[] = {
    {0, 33, 1}, 	 // [RD_DIS.KEY1] rd_dis of BLOCK_KEY1,
};

static const esp_loader_efuse_desc_t RD_DIS_BLOCK_KEY2[] = {
    {0, 34, 1}, 	 // [RD_DIS.KEY2] rd_dis of BLOCK_KEY2,
};

static const esp_loader_efuse_desc_t RD_DIS_BLOCK_KEY3[] = {
    {0, 35, 1}, 	 // [RD_DIS.KEY3] rd_dis of BLOCK_KEY3,
};

static const esp_loader_efuse_desc_t RD_DIS_BLOCK_KEY4[] = {
    {0, 36, 1}, 	 // [RD_DIS.KEY4] rd_dis of BLOCK_KEY4,
};

static const esp_loader_efuse_desc_t RD_DIS_BLOCK_KEY5[] = {
    {0, 37, 1}, 	 // [RD_DIS.KEY5] rd_dis of BLOCK_KEY5,
};

static const esp_loader_efuse_desc_t RD_DIS_BLOCK_SYS_DATA2[] = {
    {0, 38, 1}, 	 // [RD_DIS.SYS_DATA_PART2] rd_dis of BLOCK_SYS_DATA2,
};

static const esp_loader_efuse_desc_t DIS_ICACHE[] = {
    {0, 40, 1}, 	 // [] Set this bit to disable Icache,
};

static const esp_loader_efuse_desc_t DIS_USB_JTAG[] = {
    {0, 41, 1}, 	 // [] Set this bit to disable function of usb switch to jtag in module of usb device,
};

static const esp_loader_efuse_desc_t DIS_DOWNLOAD_ICACHE[] = {
    {0, 42, 1}, 	 // [] Set this bit to disable Icache in download mode (boot_mode[3:0] is 0; 1; 2; 3; 6; 7),
};

static const esp_loader_efuse_desc_t DIS_USB_SERIAL_JTAG[] = {
    {0, 43, 1}, 	 // [DIS_USB_DEVICE] USB-Serial-JTAG {0: "Enable"; 1: "Disable"},
};

static const esp_loader_efuse_desc_t DIS_FORCE_DOWNLOAD[] = {
    {0, 44, 1}, 	 // [] Set this bit to disable the function that forces chip into download mode,
};

static const esp_loader_efuse_desc_t DIS_TWAI[] = {
    {0, 46, 1}, 	 // [DIS_CAN] Set this bit to disable CAN function,
};

static const esp_loader_efuse_desc_t JTAG_SEL_ENABLE[] = {
    {0, 47, 1}, 	 // [] Set this bit to enable selection between usb_to_jtag and pad_to_jtag through strapping gpio10 when both reg_dis_usb_jtag and reg_dis_pad_jtag are equal to 0,
};

static const esp_loader_efuse_desc_t SOFT_DIS_JTAG[] = {
    {0, 48, 3}, 	 // [] Set these bits to disable JTAG in the soft way (odd number 1 means disable ). JTAG can be enabled in HMAC module,
};

static const esp_loader_efuse_desc_t DIS_PAD_JTAG[] = {
    {0, 51, 1}, 	 // [] Set this bit to disable JTAG in the hard way. JTAG is disabled permanently,
};

static const esp_loader_efuse_desc_t DIS_DOWNLOAD_MANUAL_ENCRYPT[] = {
    {0, 52, 1}, 	 // [] Set this bit to disable flash encryption when in download boot modes,
};

static const esp_loader_efuse_desc_t USB_EXCHG_PINS[] = {
    {0, 57, 1}, 	 // [] Set this bit to exchange USB D+ and D- pins,
};

static const esp_loader_efuse_desc_t VDD_SPI_AS_GPIO[] = {
    {0, 58, 1}, 	 // [] Set this bit to vdd spi pin function as gpio,
};

static const esp_loader_efuse_desc_t WDT_DELAY_SEL[] = {
    {0, 80, 2}, 	 // [] RTC watchdog timeout threshold; in unit of slow clock cycle {0: "40000"; 1: "80000"; 2: "160000"; 3: "320000"},
};

static const esp_loader_efuse_desc_t SPI_BOOT_CRYPT_CNT[] = {
    {0, 82, 3}, 	 // [] Enables flash encryption when 1 or 3 bits are set and disables otherwise {0: "Disable"; 1: "Enable"; 3: "Disable"; 7: "Enable"},
};

static const esp_loader_efuse_desc_t SECURE_BOOT_KEY_REVOKE0[] = {
    {0, 85, 1}, 	 // [] Revoke 1st secure boot key,
};

static const esp_loader_efuse_desc_t SECURE_BOOT_KEY_REVOKE1[] = {
    {0, 86, 1}, 	 // [] Revoke 2nd secure boot key,
};

static const esp_loader_efuse_desc_t SECURE_BOOT_KEY_REVOKE2[] = {
    {0, 87, 1}, 	 // [] Revoke 3rd secure boot key,
};

static const esp_loader_efuse_desc_t KEY_PURPOSE_0[] = {
    {0, 88, 4}, 	 // [KEY0_PURPOSE] Purpose of Key0,
};

static const esp_loader_efuse_desc_t KEY_PURPOSE_1[] = {
    {0, 92, 4}, 	 // [KEY1_PURPOSE] Purpose of Key1,
};

static const esp_loader_efuse_desc_t KEY_PURPOSE_2[] = {
    {0, 96, 4}, 	 // [KEY2_PURPOSE] Purpose of Key2,
};

static const esp_loader_efuse_desc_t KEY_PURPOSE_3[] = {
    {0, 100, 4}, 	 // [KEY3_PURPOSE] Purpose of Key3,
};

static const esp_loader_efuse_desc_t KEY_PURPOSE_4[] = {
    {0, 104, 4}, 	 // [KEY4_PURPOSE] Purpose of Key4,
};

static const esp_loader_efuse_desc_t KEY_PURPOSE_5[] = {
    {0, 108, 4}, 	 // [KEY5_PURPOSE] Purpose of Key5,
};

static const esp_loader_efuse_desc_t SECURE_BOOT_EN[] = {
    {0, 116, 1}, 	 // [] Set this bit to enable secure boot,
};

static const esp_loader_efuse_desc_t SECURE_BOOT_AGGRESSIVE_REVOKE[] = {
    {0, 117, 1}, 	 // [] Set this bit to enable revoking aggressive secure boot,
};

static const esp_loader_efuse_desc_t FLASH_TPUW[] = {
    {0, 124, 4}, 	 // [] Configures flash waiting time after power-up; in unit of ms. If the value is less than 15; the waiting time is the configurable value; Otherwise; the waiting time is twice the configurable value,
};

static const esp_loader_efuse_desc_t DIS_DOWNLOAD_MODE[] = {
    {0, 128, 1}, 	 // [] Set this bit to disable download mode (boot_mode[3:0] = 0; 1; 2; 3; 6; 7),
};

static const esp_loader_efuse_desc_t DIS_DIRECT_BOOT[] = {
    {0, 129, 1}, 	 // [DIS_LEGACY_SPI_BOOT] Disable direct boot mode,
};

static const esp_loader_efuse_desc_t DIS_USB_SERIAL_JTAG_ROM_PRINT[] = {
    {0, 130, 1}, 	 // [UART_PRINT_CHANNEL] USB printing {0: "Enable"; 1: "Disable"},
};

static const esp_loader_efuse_desc_t DIS_USB_SERIAL_JTAG_DOWNLOAD_MODE[] = {
    {0, 132, 1}, 	 // [DIS_USB_DOWNLOAD_MODE] Disable UART download mode through USB-Serial-JTAG,
};

static const esp_loader_efuse_desc_t ENABLE_SECURITY_DOWNLOAD[] = {
    {0, 133, 1}, 	 // [] Set this bit to enable secure UART download mode,
};

static const esp_loader_efuse_desc_t UART_PRINT_CONTROL[] = {
    {0, 134, 2}, 	 // [] Set the default UARTboot message output mode {0: "Enable"; 1: "Enable when GPIO8 is low at reset"; 2: "Enable when GPIO8 is high at reset"; 3: "Disable"},
};

static const esp_loader_efuse_desc_t FORCE_SEND_RESUME[] = {
    {0, 141, 1}, 	 // [] Set this bit to force ROM code to send a resume command during SPI boot,
};

static const esp_loader_efuse_desc_t SECURE_VERSION[] = {
    {0, 142, 16}, 	 // [] Secure version (used by ESP-IDF anti-rollback feature),
};

static const esp_loader_efuse_desc_t ERR_RST_ENABLE[] = {
    {0, 159, 1}, 	 // [] Use BLOCK0 to check error record registers {0: "without check"; 1: "with check"},
};

static const esp_loader_efuse_desc_t DISABLE_WAFER_VERSION_MAJOR[] = {
    {0, 160, 1}, 	 // [] Disables check of wafer version major,
};

static const esp_loader_efuse_desc_t DISABLE_BLK_VERSION_MAJOR[] = {
    {0, 161, 1}, 	 // [] Disables check of blk version major,
};

static const esp_loader_efuse_desc_t MAC[] = {
    {1, 40, 8}, 	 // [MAC_FACTORY] MAC address,
    {1, 32, 8}, 	 // [MAC_FACTORY] MAC address,
    {1, 24, 8}, 	 // [MAC_FACTORY] MAC address,
    {1, 16, 8}, 	 // [MAC_FACTORY] MAC address,
    {1, 8, 8}, 	 // [MAC_FACTORY] MAC address,
    {1, 0, 8}, 	 // [MAC_FACTORY] MAC address,
};

static const esp_loader_efuse_desc_t SPI_PAD_CONFIG_CLK[] = {
    {1, 48, 6}, 	 // [] SPI PAD CLK,
};

static const esp_loader_efuse_desc_t SPI_PAD_CONFIG_Q[] = {
    {1, 54, 6}, 	 // [] SPI PAD Q(D1),
};

static const esp_loader_efuse_desc_t SPI_PAD_CONFIG_D[] = {
    {1, 60, 6}, 	 // [] SPI PAD D(D0),
};

static const esp_loader_efuse_desc_t SPI_PAD_CONFIG_CS[] = {
    {1, 66, 6}, 	 // [] SPI PAD CS,
};

static const esp_loader_efuse_desc_t SPI_PAD_CONFIG_HD[] = {
    {1, 72, 6}, 	 // [] SPI PAD HD(D3),
};

static const esp_loader_efuse_desc_t SPI_PAD_CONFIG_WP[] = {
    {1, 78, 6}, 	 // [] SPI PAD WP(D2),
};

static const esp_loader_efuse_desc_t SPI_PAD_CONFIG_DQS[] = {
    {1, 84, 6}, 	 // [] SPI PAD DQS,
};

static const esp_loader_efuse_desc_t SPI_PAD_CONFIG_D4[] = {
    {1, 90, 6}, 	 // [] SPI PAD D4,
};

static const esp_loader_efuse_desc_t SPI_PAD_CONFIG_D5[] = {
    {1, 96, 6}, 	 // [] SPI PAD D5,
};

static const esp_loader_efuse_desc_t SPI_PAD_CONFIG_D6[] = {
    {1, 102, 6}, 	 // [] SPI PAD D6,
};

static const esp_loader_efuse_desc_t SPI_PAD_CONFIG_D7[] = {
    {1, 108, 6}, 	 // [] SPI PAD D7,
};

static const esp_loader_efuse_desc_t WAFER_VERSION_MINOR_LO[] = {
    {1, 114, 3}, 	 // [] WAFER_VERSION_MINOR least significant bits,
};

static const esp_loader_efuse_desc_t PKG_VERSION[] = {
    {1, 117, 3}, 	 // [] Package version,
};

static const esp_loader_efuse_desc_t BLK_VERSION_MINOR[] = {
    {1, 120, 3}, 	 // [] BLK_VERSION_MINOR,
};

static const esp_loader_efuse_desc_t FLASH_CAP[] = {
    {1, 123, 3}, 	 // [] Flash capacity {0: "None"; 1: "4M"; 2: "2M"; 3: "1M"; 4: "8M"},
};

static const esp_loader_efuse_desc_t FLASH_TEMP[] = {
    {1, 126, 2}, 	 // [] Flash temperature {0: "None"; 1: "105C"; 2: "85C"},
};

static const esp_loader_efuse_desc_t FLASH_VENDOR[] = {
    {1, 128, 3}, 	 // [] Flash vendor {0: "None"; 1: "XMC"; 2: "GD"; 3: "FM"; 4: "TT"; 5: "ZBIT"},
};

static const esp_loader_efuse_desc_t K_RTC_LDO[] = {
    {1, 135, 7}, 	 // [] BLOCK1 K_RTC_LDO,
};

static const esp_loader_efuse_desc_t K_DIG_LDO[] = {
    {1, 142, 7}, 	 // [] BLOCK1 K_DIG_LDO,
};

static const esp_loader_efuse_desc_t V_RTC_DBIAS20[] = {
    {1, 149, 8}, 	 // [] BLOCK1 voltage of rtc dbias20,
};

static const esp_loader_efuse_desc_t V_DIG_DBIAS20[] = {
    {1, 157, 8}, 	 // [] BLOCK1 voltage of digital dbias20,
};

static const esp_loader_efuse_desc_t DIG_DBIAS_HVT[] = {
    {1, 165, 5}, 	 // [] BLOCK1 digital dbias when hvt,
};

static const esp_loader_efuse_desc_t THRES_HVT[] = {
    {1, 170, 10}, 	 // [] BLOCK1 pvt threshold when hvt,
};

static const esp_loader_efuse_desc_t WAFER_VERSION_MINOR_HI[] = {
    {1, 183, 1}, 	 // [] WAFER_VERSION_MINOR most significant bit,
};

static const esp_loader_efuse_desc_t WAFER_VERSION_MAJOR[] = {
    {1, 184, 2}, 	 // [] WAFER_VERSION_MAJOR,
};

static const esp_loader_efuse_desc_t OPTIONAL_UNIQUE_ID[] = {
    {2, 0, 128}, 	 // [] Optional unique 128-bit ID,
};

static const esp_loader_efuse_desc_t BLK_VERSION_MAJOR[] = {
    {2, 128, 2}, 	 // [] BLK_VERSION_MAJOR of BLOCK2 {0: "No calibration"; 1: "With calibration"},
};

static const esp_loader_efuse_desc_t TEMP_CALIB[] = {
    {2, 131, 9}, 	 // [] Temperature calibration data,
};

static const esp_loader_efuse_desc_t OCODE[] = {
    {2, 140, 8}, 	 // [] ADC OCode,
};

static const esp_loader_efuse_desc_t ADC1_INIT_CODE_ATTEN0[] = {
    {2, 148, 10}, 	 // [] ADC1 init code at atten0,
};

static const esp_loader_efuse_desc_t ADC1_INIT_CODE_ATTEN1[] = {
    {2, 158, 10}, 	 // [] ADC1 init code at atten1,
};

static const esp_loader_efuse_desc_t ADC1_INIT_CODE_ATTEN2[] = {
    {2, 168, 10}, 	 // [] ADC1 init code at atten2,
};

static const esp_loader_efuse_desc_t ADC1_INIT_CODE_ATTEN3[] = {
    {2, 178, 10}, 	 // [] ADC1 init code at atten3,
};

static const esp_loader_efuse_desc_t ADC1_CAL_VOL_ATTEN0[] = {
    {2, 188, 10}, 	 // [] ADC1 calibration voltage at atten0,
};

static const esp_loader_efuse_desc_t ADC1_CAL_VOL_ATTEN1[] = {
    {2, 198, 10}, 	 // [] ADC1 calibration voltage at atten1,
};

static const esp_loader_efuse_desc_t ADC1_CAL_VOL_ATTEN2[] = {
    {2, 208, 10}, 	 // [] ADC1 calibration voltage at atten2,
};

static const esp_loader_efuse_desc_t ADC1_CAL_VOL_ATTEN3[] = {
    {2, 218, 10}, 	 // [] ADC1 calibration voltage at atten3,
};

static const esp_loader_efuse_desc_t USER_DATA[] = {
    {3, 0, 256}, 	 // [BLOCK_USR_DATA] User data,
};

static const esp_loader_efuse_desc_t USER_DATA_MAC_CUSTOM[] = {
    {3, 200, 48}, 	 // [MAC_CUSTOM CUSTOM_MAC] Custom MAC address,
};

static const esp_loader_efuse_desc_t KEY0[] = {
    {4, 0, 256}, 	 // [BLOCK_KEY0] Key0 or user data,
};

static const esp_loader_efuse_desc_t KEY1[] = {
    {5, 0, 256}, 	 // [BLOCK_KEY1] Key1 or user data,
};

static const esp_loader_efuse_desc_t KEY2[] = {
    {6, 0, 256}, 	 // [BLOCK_KEY2] Key2 or user data,
};

static const esp_loader_efuse_desc_t KEY3[] = {
    {7, 0, 256}, 	 // [BLOCK_KEY3] Key3 or user data,
};

static const esp_loader_efuse_desc_t KEY4[] = {
    {8, 0, 256}, 	 // [BLOCK_KEY4] Key4 or user data,
};

static const esp_loader_efuse_desc_t KEY5[] = {
    {9, 0, 256}, 	 // [BLOCK_KEY5] Key5 or user data,
};

static const esp_loader_efuse_desc_t SYS_DATA_PART2[] = {
    {10, 0, 256}, 	 // [BLOCK_SYS_DATA2] System data part 2 (reserved),
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS[] = {
    &WR_DIS[0],    		// [] Disable programming of individual eFuses
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_RD_DIS[] = {
    &WR_DIS_RD_DIS[0],    		// [] wr_dis of RD_DIS
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DIS_ICACHE[] = {
    &WR_DIS_DIS_ICACHE[0],    		// [] wr_dis of DIS_ICACHE
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DIS_USB_JTAG[] = {
    &WR_DIS_DIS_USB_JTAG[0],    		// [] wr_dis of DIS_USB_JTAG
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DIS_DOWNLOAD_ICACHE[] = {
    &WR_DIS_DIS_DOWNLOAD_ICACHE[0],    		// [] wr_dis of DIS_DOWNLOAD_ICACHE
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DIS_USB_SERIAL_JTAG[] = {
    &WR_DIS_DIS_USB_SERIAL_JTAG[0],    		// [WR_DIS.DIS_USB_DEVICE] wr_dis of DIS_USB_SERIAL_JTAG
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DIS_FORCE_DOWNLOAD[] = {
    &WR_DIS_DIS_FORCE_DOWNLOAD[0],    		// [] wr_dis of DIS_FORCE_DOWNLOAD
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DIS_TWAI[] = {
    &WR_DIS_DIS_TWAI[0],    		// [WR_DIS.DIS_CAN] wr_dis of DIS_TWAI
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_JTAG_SEL_ENABLE[] = {
    &WR_DIS_JTAG_SEL_ENABLE[0],    		// [] wr_dis of JTAG_SEL_ENABLE
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DIS_PAD_JTAG[] = {
    &WR_DIS_DIS_PAD_JTAG[0],    		// [] wr_dis of DIS_PAD_JTAG
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DIS_DOWNLOAD_MANUAL_ENCRYPT[] = {
    &WR_DIS_DIS_DOWNLOAD_MANUAL_ENCRYPT[0],    		// [] wr_dis of DIS_DOWNLOAD_MANUAL_ENCRYPT
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_WDT_DELAY_SEL[] = {
    &WR_DIS_WDT_DELAY_SEL[0],    		// [] wr_dis of WDT_DELAY_SEL
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SPI_BOOT_CRYPT_CNT[] = {
    &WR_DIS_SPI_BOOT_CRYPT_CNT[0],    		// [] wr_dis of SPI_BOOT_CRYPT_CNT
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SECURE_BOOT_KEY_REVOKE0[] = {
    &WR_DIS_SECURE_BOOT_KEY_REVOKE0[0],    		// [] wr_dis of SECURE_BOOT_KEY_REVOKE0
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SECURE_BOOT_KEY_REVOKE1[] = {
    &WR_DIS_SECURE_BOOT_KEY_REVOKE1[0],    		// [] wr_dis of SECURE_BOOT_KEY_REVOKE1
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SECURE_BOOT_KEY_REVOKE2[] = {
    &WR_DIS_SECURE_BOOT_KEY_REVOKE2[0],    		// [] wr_dis of SECURE_BOOT_KEY_REVOKE2
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_KEY_PURPOSE_0[] = {
    &WR_DIS_KEY_PURPOSE_0[0],    		// [WR_DIS.KEY0_PURPOSE] wr_dis of KEY_PURPOSE_0
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_KEY_PURPOSE_1[] = {
    &WR_DIS_KEY_PURPOSE_1[0],    		// [WR_DIS.KEY1_PURPOSE] wr_dis of KEY_PURPOSE_1
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_KEY_PURPOSE_2[] = {
    &WR_DIS_KEY_PURPOSE_2[0],    		// [WR_DIS.KEY2_PURPOSE] wr_dis of KEY_PURPOSE_2
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_KEY_PURPOSE_3[] = {
    &WR_DIS_KEY_PURPOSE_3[0],    		// [WR_DIS.KEY3_PURPOSE] wr_dis of KEY_PURPOSE_3
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_KEY_PURPOSE_4[] = {
    &WR_DIS_KEY_PURPOSE_4[0],    		// [WR_DIS.KEY4_PURPOSE] wr_dis of KEY_PURPOSE_4
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_KEY_PURPOSE_5[] = {
    &WR_DIS_KEY_PURPOSE_5[0],    		// [WR_DIS.KEY5_PURPOSE] wr_dis of KEY_PURPOSE_5
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SECURE_BOOT_EN[] = {
    &WR_DIS_SECURE_BOOT_EN[0],    		// [] wr_dis of SECURE_BOOT_EN
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SECURE_BOOT_AGGRESSIVE_REVOKE[] = {
    &WR_DIS_SECURE_BOOT_AGGRESSIVE_REVOKE[0],    		// [] wr_dis of SECURE_BOOT_AGGRESSIVE_REVOKE
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_FLASH_TPUW[] = {
    &WR_DIS_FLASH_TPUW[0],    		// [] wr_dis of FLASH_TPUW
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DIS_DOWNLOAD_MODE[] = {
    &WR_DIS_DIS_DOWNLOAD_MODE[0],    		// [] wr_dis of DIS_DOWNLOAD_MODE
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DIS_DIRECT_BOOT[] = {
    &WR_DIS_DIS_DIRECT_BOOT[0],    		// [WR_DIS.DIS_LEGACY_SPI_BOOT] wr_dis of DIS_DIRECT_BOOT
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DIS_USB_SERIAL_JTAG_ROM_PRINT[] = {
    &WR_DIS_DIS_USB_SERIAL_JTAG_ROM_PRINT[0],    		// [WR_DIS.UART_PRINT_CHANNEL] wr_dis of DIS_USB_SERIAL_JTAG_ROM_PRINT
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DIS_USB_SERIAL_JTAG_DOWNLOAD_MODE[] = {
    &WR_DIS_DIS_USB_SERIAL_JTAG_DOWNLOAD_MODE[0],    		// [WR_DIS.DIS_USB_DOWNLOAD_MODE] wr_dis of DIS_USB_SERIAL_JTAG_DOWNLOAD_MODE
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_ENABLE_SECURITY_DOWNLOAD[] = {
    &WR_DIS_ENABLE_SECURITY_DOWNLOAD[0],    		// [] wr_dis of ENABLE_SECURITY_DOWNLOAD
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_UART_PRINT_CONTROL[] = {
    &WR_DIS_UART_PRINT_CONTROL[0],    		// [] wr_dis of UART_PRINT_CONTROL
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_FORCE_SEND_RESUME[] = {
    &WR_DIS_FORCE_SEND_RESUME[0],    		// [] wr_dis of FORCE_SEND_RESUME
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SECURE_VERSION[] = {
    &WR_DIS_SECURE_VERSION[0],    		// [] wr_dis of SECURE_VERSION
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_ERR_RST_ENABLE[] = {
    &WR_DIS_ERR_RST_ENABLE[0],    		// [] wr_dis of ERR_RST_ENABLE
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DISABLE_WAFER_VERSION_MAJOR[] = {
    &WR_DIS_DISABLE_WAFER_VERSION_MAJOR[0],    		// [] wr_dis of DISABLE_WAFER_VERSION_MAJOR
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DISABLE_BLK_VERSION_MAJOR[] = {
    &WR_DIS_DISABLE_BLK_VERSION_MAJOR[0],    		// [] wr_dis of DISABLE_BLK_VERSION_MAJOR
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_BLK1[] = {
    &WR_DIS_BLK1[0],    		// [] wr_dis of BLOCK1
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_MAC[] = {
    &WR_DIS_MAC[0],    		// [WR_DIS.MAC_FACTORY] wr_dis of MAC
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SPI_PAD_CONFIG_CLK[] = {
    &WR_DIS_SPI_PAD_CONFIG_CLK[0],    		// [] wr_dis of SPI_PAD_CONFIG_CLK
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SPI_PAD_CONFIG_Q[] = {
    &WR_DIS_SPI_PAD_CONFIG_Q[0],    		// [] wr_dis of SPI_PAD_CONFIG_Q
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SPI_PAD_CONFIG_D[] = {
    &WR_DIS_SPI_PAD_CONFIG_D[0],    		// [] wr_dis of SPI_PAD_CONFIG_D
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SPI_PAD_CONFIG_CS[] = {
    &WR_DIS_SPI_PAD_CONFIG_CS[0],    		// [] wr_dis of SPI_PAD_CONFIG_CS
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SPI_PAD_CONFIG_HD[] = {
    &WR_DIS_SPI_PAD_CONFIG_HD[0],    		// [] wr_dis of SPI_PAD_CONFIG_HD
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SPI_PAD_CONFIG_WP[] = {
    &WR_DIS_SPI_PAD_CONFIG_WP[0],    		// [] wr_dis of SPI_PAD_CONFIG_WP
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SPI_PAD_CONFIG_DQS[] = {
    &WR_DIS_SPI_PAD_CONFIG_DQS[0],    		// [] wr_dis of SPI_PAD_CONFIG_DQS
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SPI_PAD_CONFIG_D4[] = {
    &WR_DIS_SPI_PAD_CONFIG_D4[0],    		// [] wr_dis of SPI_PAD_CONFIG_D4
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SPI_PAD_CONFIG_D5[] = {
    &WR_DIS_SPI_PAD_CONFIG_D5[0],    		// [] wr_dis of SPI_PAD_CONFIG_D5
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SPI_PAD_CONFIG_D6[] = {
    &WR_DIS_SPI_PAD_CONFIG_D6[0],    		// [] wr_dis of SPI_PAD_CONFIG_D6
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SPI_PAD_CONFIG_D7[] = {
    &WR_DIS_SPI_PAD_CONFIG_D7[0],    		// [] wr_dis of SPI_PAD_CONFIG_D7
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_WAFER_VERSION_MINOR_LO[] = {
    &WR_DIS_WAFER_VERSION_MINOR_LO[0],    		// [] wr_dis of WAFER_VERSION_MINOR_LO
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_PKG_VERSION[] = {
    &WR_DIS_PKG_VERSION[0],    		// [] wr_dis of PKG_VERSION
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_BLK_VERSION_MINOR[] = {
    &WR_DIS_BLK_VERSION_MINOR[0],    		// [] wr_dis of BLK_VERSION_MINOR
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_FLASH_CAP[] = {
    &WR_DIS_FLASH_CAP[0],    		// [] wr_dis of FLASH_CAP
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_FLASH_TEMP[] = {
    &WR_DIS_FLASH_TEMP[0],    		// [] wr_dis of FLASH_TEMP
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_FLASH_VENDOR[] = {
    &WR_DIS_FLASH_VENDOR[0],    		// [] wr_dis of FLASH_VENDOR
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_K_RTC_LDO[] = {
    &WR_DIS_K_RTC_LDO[0],    		// [] wr_dis of K_RTC_LDO
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_K_DIG_LDO[] = {
    &WR_DIS_K_DIG_LDO[0],    		// [] wr_dis of K_DIG_LDO
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_V_RTC_DBIAS20[] = {
    &WR_DIS_V_RTC_DBIAS20[0],    		// [] wr_dis of V_RTC_DBIAS20
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_V_DIG_DBIAS20[] = {
    &WR_DIS_V_DIG_DBIAS20[0],    		// [] wr_dis of V_DIG_DBIAS20
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_DIG_DBIAS_HVT[] = {
    &WR_DIS_DIG_DBIAS_HVT[0],    		// [] wr_dis of DIG_DBIAS_HVT
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_THRES_HVT[] = {
    &WR_DIS_THRES_HVT[0],    		// [] wr_dis of THRES_HVT
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_WAFER_VERSION_MINOR_HI[] = {
    &WR_DIS_WAFER_VERSION_MINOR_HI[0],    		// [] wr_dis of WAFER_VERSION_MINOR_HI
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_WAFER_VERSION_MAJOR[] = {
    &WR_DIS_WAFER_VERSION_MAJOR[0],    		// [] wr_dis of WAFER_VERSION_MAJOR
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SYS_DATA_PART1[] = {
    &WR_DIS_SYS_DATA_PART1[0],    		// [] wr_dis of BLOCK2
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_OPTIONAL_UNIQUE_ID[] = {
    &WR_DIS_OPTIONAL_UNIQUE_ID[0],    		// [] wr_dis of OPTIONAL_UNIQUE_ID
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_BLK_VERSION_MAJOR[] = {
    &WR_DIS_BLK_VERSION_MAJOR[0],    		// [] wr_dis of BLK_VERSION_MAJOR
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_TEMP_CALIB[] = {
    &WR_DIS_TEMP_CALIB[0],    		// [] wr_dis of TEMP_CALIB
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_OCODE[] = {
    &WR_DIS_OCODE[0],    		// [] wr_dis of OCODE
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_ADC1_INIT_CODE_ATTEN0[] = {
    &WR_DIS_ADC1_INIT_CODE_ATTEN0[0],    		// [] wr_dis of ADC1_INIT_CODE_ATTEN0
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_ADC1_INIT_CODE_ATTEN1[] = {
    &WR_DIS_ADC1_INIT_CODE_ATTEN1[0],    		// [] wr_dis of ADC1_INIT_CODE_ATTEN1
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_ADC1_INIT_CODE_ATTEN2[] = {
    &WR_DIS_ADC1_INIT_CODE_ATTEN2[0],    		// [] wr_dis of ADC1_INIT_CODE_ATTEN2
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_ADC1_INIT_CODE_ATTEN3[] = {
    &WR_DIS_ADC1_INIT_CODE_ATTEN3[0],    		// [] wr_dis of ADC1_INIT_CODE_ATTEN3
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_ADC1_CAL_VOL_ATTEN0[] = {
    &WR_DIS_ADC1_CAL_VOL_ATTEN0[0],    		// [] wr_dis of ADC1_CAL_VOL_ATTEN0
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_ADC1_CAL_VOL_ATTEN1[] = {
    &WR_DIS_ADC1_CAL_VOL_ATTEN1[0],    		// [] wr_dis of ADC1_CAL_VOL_ATTEN1
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_ADC1_CAL_VOL_ATTEN2[] = {
    &WR_DIS_ADC1_CAL_VOL_ATTEN2[0],    		// [] wr_dis of ADC1_CAL_VOL_ATTEN2
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_ADC1_CAL_VOL_ATTEN3[] = {
    &WR_DIS_ADC1_CAL_VOL_ATTEN3[0],    		// [] wr_dis of ADC1_CAL_VOL_ATTEN3
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_BLOCK_USR_DATA[] = {
    &WR_DIS_BLOCK_USR_DATA[0],    		// [WR_DIS.USER_DATA] wr_dis of BLOCK_USR_DATA
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_CUSTOM_MAC[] = {
    &WR_DIS_CUSTOM_MAC[0],    		// [WR_DIS.MAC_CUSTOM WR_DIS.USER_DATA_MAC_CUSTOM] wr_dis of CUSTOM_MAC
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_BLOCK_KEY0[] = {
    &WR_DIS_BLOCK_KEY0[0],    		// [WR_DIS.KEY0] wr_dis of BLOCK_KEY0
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_BLOCK_KEY1[] = {
    &WR_DIS_BLOCK_KEY1[0],    		// [WR_DIS.KEY1] wr_dis of BLOCK_KEY1
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_BLOCK_KEY2[] = {
    &WR_DIS_BLOCK_KEY2[0],    		// [WR_DIS.KEY2] wr_dis of BLOCK_KEY2
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_BLOCK_KEY3[] = {
    &WR_DIS_BLOCK_KEY3[0],    		// [WR_DIS.KEY3] wr_dis of BLOCK_KEY3
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_BLOCK_KEY4[] = {
    &WR_DIS_BLOCK_KEY4[0],    		// [WR_DIS.KEY4] wr_dis of BLOCK_KEY4
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_BLOCK_KEY5[] = {
    &WR_DIS_BLOCK_KEY5[0],    		// [WR_DIS.KEY5] wr_dis of BLOCK_KEY5
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_BLOCK_SYS_DATA2[] = {
    &WR_DIS_BLOCK_SYS_DATA2[0],    		// [WR_DIS.SYS_DATA_PART2] wr_dis of BLOCK_SYS_DATA2
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_USB_EXCHG_PINS[] = {
    &WR_DIS_USB_EXCHG_PINS[0],    		// [] wr_dis of USB_EXCHG_PINS
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_VDD_SPI_AS_GPIO[] = {
    &WR_DIS_VDD_SPI_AS_GPIO[0],    		// [] wr_dis of VDD_SPI_AS_GPIO
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WR_DIS_SOFT_DIS_JTAG[] = {
    &WR_DIS_SOFT_DIS_JTAG[0],    		// [] wr_dis of SOFT_DIS_JTAG
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_RD_DIS[] = {
    &RD_DIS[0],    		// [] Disable reading from BlOCK4-10
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_RD_DIS_BLOCK_KEY0[] = {
    &RD_DIS_BLOCK_KEY0[0],    		// [RD_DIS.KEY0] rd_dis of BLOCK_KEY0
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_RD_DIS_BLOCK_KEY1[] = {
    &RD_DIS_BLOCK_KEY1[0],    		// [RD_DIS.KEY1] rd_dis of BLOCK_KEY1
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_RD_DIS_BLOCK_KEY2[] = {
    &RD_DIS_BLOCK_KEY2[0],    		// [RD_DIS.KEY2] rd_dis of BLOCK_KEY2
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_RD_DIS_BLOCK_KEY3[] = {
    &RD_DIS_BLOCK_KEY3[0],    		// [RD_DIS.KEY3] rd_dis of BLOCK_KEY3
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_RD_DIS_BLOCK_KEY4[] = {
    &RD_DIS_BLOCK_KEY4[0],    		// [RD_DIS.KEY4] rd_dis of BLOCK_KEY4
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_RD_DIS_BLOCK_KEY5[] = {
    &RD_DIS_BLOCK_KEY5[0],    		// [RD_DIS.KEY5] rd_dis of BLOCK_KEY5
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_RD_DIS_BLOCK_SYS_DATA2[] = {
    &RD_DIS_BLOCK_SYS_DATA2[0],    		// [RD_DIS.SYS_DATA_PART2] rd_dis of BLOCK_SYS_DATA2
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DIS_ICACHE[] = {
    &DIS_ICACHE[0],    		// [] Set this bit to disable Icache
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DIS_USB_JTAG[] = {
    &DIS_USB_JTAG[0],    		// [] Set this bit to disable function of usb switch to jtag in module of usb device
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DIS_DOWNLOAD_ICACHE[] = {
    &DIS_DOWNLOAD_ICACHE[0],    		// [] Set this bit to disable Icache in download mode (boot_mode[3:0] is 0; 1; 2; 3; 6; 7)
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DIS_USB_SERIAL_JTAG[] = {
    &DIS_USB_SERIAL_JTAG[0],    		// [DIS_USB_DEVICE] USB-Serial-JTAG {0: "Enable"; 1: "Disable"}
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DIS_FORCE_DOWNLOAD[] = {
    &DIS_FORCE_DOWNLOAD[0],    		// [] Set this bit to disable the function that forces chip into download mode
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DIS_TWAI[] = {
    &DIS_TWAI[0],    		// [DIS_CAN] Set this bit to disable CAN function
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_JTAG_SEL_ENABLE[] = {
    &JTAG_SEL_ENABLE[0],    		// [] Set this bit to enable selection between usb_to_jtag and pad_to_jtag through strapping gpio10 when both reg_dis_usb_jtag and reg_dis_pad_jtag are equal to 0
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SOFT_DIS_JTAG[] = {
    &SOFT_DIS_JTAG[0],    		// [] Set these bits to disable JTAG in the soft way (odd number 1 means disable ). JTAG can be enabled in HMAC module
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DIS_PAD_JTAG[] = {
    &DIS_PAD_JTAG[0],    		// [] Set this bit to disable JTAG in the hard way. JTAG is disabled permanently
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DIS_DOWNLOAD_MANUAL_ENCRYPT[] = {
    &DIS_DOWNLOAD_MANUAL_ENCRYPT[0],    		// [] Set this bit to disable flash encryption when in download boot modes
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_USB_EXCHG_PINS[] = {
    &USB_EXCHG_PINS[0],    		// [] Set this bit to exchange USB D+ and D- pins
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_VDD_SPI_AS_GPIO[] = {
    &VDD_SPI_AS_GPIO[0],    		// [] Set this bit to vdd spi pin function as gpio
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WDT_DELAY_SEL[] = {
    &WDT_DELAY_SEL[0],    		// [] RTC watchdog timeout threshold; in unit of slow clock cycle {0: "40000"; 1: "80000"; 2: "160000"; 3: "320000"}
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SPI_BOOT_CRYPT_CNT[] = {
    &SPI_BOOT_CRYPT_CNT[0],    		// [] Enables flash encryption when 1 or 3 bits are set and disables otherwise {0: "Disable"; 1: "Enable"; 3: "Disable"; 7: "Enable"}
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SECURE_BOOT_KEY_REVOKE0[] = {
    &SECURE_BOOT_KEY_REVOKE0[0],    		// [] Revoke 1st secure boot key
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SECURE_BOOT_KEY_REVOKE1[] = {
    &SECURE_BOOT_KEY_REVOKE1[0],    		// [] Revoke 2nd secure boot key
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SECURE_BOOT_KEY_REVOKE2[] = {
    &SECURE_BOOT_KEY_REVOKE2[0],    		// [] Revoke 3rd secure boot key
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_KEY_PURPOSE_0[] = {
    &KEY_PURPOSE_0[0],    		// [KEY0_PURPOSE] Purpose of Key0
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_KEY_PURPOSE_1[] = {
    &KEY_PURPOSE_1[0],    		// [KEY1_PURPOSE] Purpose of Key1
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_KEY_PURPOSE_2[] = {
    &KEY_PURPOSE_2[0],    		// [KEY2_PURPOSE] Purpose of Key2
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_KEY_PURPOSE_3[] = {
    &KEY_PURPOSE_3[0],    		// [KEY3_PURPOSE] Purpose of Key3
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_KEY_PURPOSE_4[] = {
    &KEY_PURPOSE_4[0],    		// [KEY4_PURPOSE] Purpose of Key4
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_KEY_PURPOSE_5[] = {
    &KEY_PURPOSE_5[0],    		// [KEY5_PURPOSE] Purpose of Key5
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SECURE_BOOT_EN[] = {
    &SECURE_BOOT_EN[0],    		// [] Set this bit to enable secure boot
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SECURE_BOOT_AGGRESSIVE_REVOKE[] = {
    &SECURE_BOOT_AGGRESSIVE_REVOKE[0],    		// [] Set this bit to enable revoking aggressive secure boot
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_FLASH_TPUW[] = {
    &FLASH_TPUW[0],    		// [] Configures flash waiting time after power-up; in unit of ms. If the value is less than 15; the waiting time is the configurable value; Otherwise; the waiting time is twice the configurable value
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DIS_DOWNLOAD_MODE[] = {
    &DIS_DOWNLOAD_MODE[0],    		// [] Set this bit to disable download mode (boot_mode[3:0] = 0; 1; 2; 3; 6; 7)
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DIS_DIRECT_BOOT[] = {
    &DIS_DIRECT_BOOT[0],    		// [DIS_LEGACY_SPI_BOOT] Disable direct boot mode
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DIS_USB_SERIAL_JTAG_ROM_PRINT[] = {
    &DIS_USB_SERIAL_JTAG_ROM_PRINT[0],    		// [UART_PRINT_CHANNEL] USB printing {0: "Enable"; 1: "Disable"}
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DIS_USB_SERIAL_JTAG_DOWNLOAD_MODE[] = {
    &DIS_USB_SERIAL_JTAG_DOWNLOAD_MODE[0],    		// [DIS_USB_DOWNLOAD_MODE] Disable UART download mode through USB-Serial-JTAG
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_ENABLE_SECURITY_DOWNLOAD[] = {
    &ENABLE_SECURITY_DOWNLOAD[0],    		// [] Set this bit to enable secure UART download mode
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_UART_PRINT_CONTROL[] = {
    &UART_PRINT_CONTROL[0],    		// [] Set the default UARTboot message output mode {0: "Enable"; 1: "Enable when GPIO8 is low at reset"; 2: "Enable when GPIO8 is high at reset"; 3: "Disable"}
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_FORCE_SEND_RESUME[] = {
    &FORCE_SEND_RESUME[0],    		// [] Set this bit to force ROM code to send a resume command during SPI boot
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SECURE_VERSION[] = {
    &SECURE_VERSION[0],    		// [] Secure version (used by ESP-IDF anti-rollback feature)
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_ERR_RST_ENABLE[] = {
    &ERR_RST_ENABLE[0],    		// [] Use BLOCK0 to check error record registers {0: "without check"; 1: "with check"}
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DISABLE_WAFER_VERSION_MAJOR[] = {
    &DISABLE_WAFER_VERSION_MAJOR[0],    		// [] Disables check of wafer version major
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DISABLE_BLK_VERSION_MAJOR[] = {
    &DISABLE_BLK_VERSION_MAJOR[0],    		// [] Disables check of blk version major
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_MAC[] = {
    &MAC[0],    		// [MAC_FACTORY] MAC address
    &MAC[1],    		// [MAC_FACTORY] MAC address
    &MAC[2],    		// [MAC_FACTORY] MAC address
    &MAC[3],    		// [MAC_FACTORY] MAC address
    &MAC[4],    		// [MAC_FACTORY] MAC address
    &MAC[5],    		// [MAC_FACTORY] MAC address
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SPI_PAD_CONFIG_CLK[] = {
    &SPI_PAD_CONFIG_CLK[0],    		// [] SPI PAD CLK
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SPI_PAD_CONFIG_Q[] = {
    &SPI_PAD_CONFIG_Q[0],    		// [] SPI PAD Q(D1)
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SPI_PAD_CONFIG_D[] = {
    &SPI_PAD_CONFIG_D[0],    		// [] SPI PAD D(D0)
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SPI_PAD_CONFIG_CS[] = {
    &SPI_PAD_CONFIG_CS[0],    		// [] SPI PAD CS
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SPI_PAD_CONFIG_HD[] = {
    &SPI_PAD_CONFIG_HD[0],    		// [] SPI PAD HD(D3)
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SPI_PAD_CONFIG_WP[] = {
    &SPI_PAD_CONFIG_WP[0],    		// [] SPI PAD WP(D2)
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SPI_PAD_CONFIG_DQS[] = {
    &SPI_PAD_CONFIG_DQS[0],    		// [] SPI PAD DQS
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SPI_PAD_CONFIG_D4[] = {
    &SPI_PAD_CONFIG_D4[0],    		// [] SPI PAD D4
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SPI_PAD_CONFIG_D5[] = {
    &SPI_PAD_CONFIG_D5[0],    		// [] SPI PAD D5
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SPI_PAD_CONFIG_D6[] = {
    &SPI_PAD_CONFIG_D6[0],    		// [] SPI PAD D6
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SPI_PAD_CONFIG_D7[] = {
    &SPI_PAD_CONFIG_D7[0],    		// [] SPI PAD D7
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WAFER_VERSION_MINOR_LO[] = {
    &WAFER_VERSION_MINOR_LO[0],    		// [] WAFER_VERSION_MINOR least significant bits
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_PKG_VERSION[] = {
    &PKG_VERSION[0],    		// [] Package version
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_BLK_VERSION_MINOR[] = {
    &BLK_VERSION_MINOR[0],    		// [] BLK_VERSION_MINOR
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_FLASH_CAP[] = {
    &FLASH_CAP[0],    		// [] Flash capacity {0: "None"; 1: "4M"; 2: "2M"; 3: "1M"; 4: "8M"}
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_FLASH_TEMP[] = {
    &FLASH_TEMP[0],    		// [] Flash temperature {0: "None"; 1: "105C"; 2: "85C"}
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_FLASH_VENDOR[] = {
    &FLASH_VENDOR[0],    		// [] Flash vendor {0: "None"; 1: "XMC"; 2: "GD"; 3: "FM"; 4: "TT"; 5: "ZBIT"}
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_K_RTC_LDO[] = {
    &K_RTC_LDO[0],    		// [] BLOCK1 K_RTC_LDO
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_K_DIG_LDO[] = {
    &K_DIG_LDO[0],    		// [] BLOCK1 K_DIG_LDO
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_V_RTC_DBIAS20[] = {
    &V_RTC_DBIAS20[0],    		// [] BLOCK1 voltage of rtc dbias20
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_V_DIG_DBIAS20[] = {
    &V_DIG_DBIAS20[0],    		// [] BLOCK1 voltage of digital dbias20
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_DIG_DBIAS_HVT[] = {
    &DIG_DBIAS_HVT[0],    		// [] BLOCK1 digital dbias when hvt
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_THRES_HVT[] = {
    &THRES_HVT[0],    		// [] BLOCK1 pvt threshold when hvt
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WAFER_VERSION_MINOR_HI[] = {
    &WAFER_VERSION_MINOR_HI[0],    		// [] WAFER_VERSION_MINOR most significant bit
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_WAFER_VERSION_MAJOR[] = {
    &WAFER_VERSION_MAJOR[0],    		// [] WAFER_VERSION_MAJOR
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_OPTIONAL_UNIQUE_ID[] = {
    &OPTIONAL_UNIQUE_ID[0],    		// [] Optional unique 128-bit ID
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_BLK_VERSION_MAJOR[] = {
    &BLK_VERSION_MAJOR[0],    		// [] BLK_VERSION_MAJOR of BLOCK2 {0: "No calibration"; 1: "With calibration"}
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_TEMP_CALIB[] = {
    &TEMP_CALIB[0],    		// [] Temperature calibration data
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_OCODE[] = {
    &OCODE[0],    		// [] ADC OCode
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_ADC1_INIT_CODE_ATTEN0[] = {
    &ADC1_INIT_CODE_ATTEN0[0],    		// [] ADC1 init code at atten0
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_ADC1_INIT_CODE_ATTEN1[] = {
    &ADC1_INIT_CODE_ATTEN1[0],    		// [] ADC1 init code at atten1
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_ADC1_INIT_CODE_ATTEN2[] = {
    &ADC1_INIT_CODE_ATTEN2[0],    		// [] ADC1 init code at atten2
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_ADC1_INIT_CODE_ATTEN3[] = {
    &ADC1_INIT_CODE_ATTEN3[0],    		// [] ADC1 init code at atten3
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_ADC1_CAL_VOL_ATTEN0[] = {
    &ADC1_CAL_VOL_ATTEN0[0],    		// [] ADC1 calibration voltage at atten0
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_ADC1_CAL_VOL_ATTEN1[] = {
    &ADC1_CAL_VOL_ATTEN1[0],    		// [] ADC1 calibration voltage at atten1
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_ADC1_CAL_VOL_ATTEN2[] = {
    &ADC1_CAL_VOL_ATTEN2[0],    		// [] ADC1 calibration voltage at atten2
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_ADC1_CAL_VOL_ATTEN3[] = {
    &ADC1_CAL_VOL_ATTEN3[0],    		// [] ADC1 calibration voltage at atten3
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_USER_DATA[] = {
    &USER_DATA[0],    		// [BLOCK_USR_DATA] User data
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_USER_DATA_MAC_CUSTOM[] = {
    &USER_DATA_MAC_CUSTOM[0],    		// [MAC_CUSTOM CUSTOM_MAC] Custom MAC address
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_KEY0[] = {
    &KEY0[0],    		// [BLOCK_KEY0] Key0 or user data
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_KEY1[] = {
    &KEY1[0],    		// [BLOCK_KEY1] Key1 or user data
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_KEY2[] = {
    &KEY2[0],    		// [BLOCK_KEY2] Key2 or user data
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_KEY3[] = {
    &KEY3[0],    		// [BLOCK_KEY3] Key3 or user data
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_KEY4[] = {
    &KEY4[0],    		// [BLOCK_KEY4] Key4 or user data
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_KEY5[] = {
    &KEY5[0],    		// [BLOCK_KEY5] Key5 or user data
    NULL
};

const esp_loader_efuse_desc_t* ESP32C3_EFUSE_SYS_DATA_PART2[] = {
    &SYS_DATA_PART2[0],    		// [BLOCK_SYS_DATA2] System data part 2 (reserved)
    NULL
};


/* Field metadata, generated from esp_loader_efuse_table.csv alongside the table above: the names
 * and protection bits the descriptors do not carry.
 *
 * The array is private; callers reach it through the field sets below, which is
 * what lets a revision that lacks the trailing fields be served by a shorter
 * view of this same array instead of a second copy of it. Nothing outside this
 * file may assume the whole array applies to every revision. */
static const esp_loader_efuse_field_info_t field_info[] = {
    { "WR_DIS",                            ESP32C3_EFUSE_WR_DIS,                            ESP_LOADER_EFUSE_BIT_NONE, ESP_LOADER_EFUSE_BIT_NONE },
    { "RD_DIS",                            ESP32C3_EFUSE_RD_DIS,                            0,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "DIS_ICACHE",                        ESP32C3_EFUSE_DIS_ICACHE,                        2,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "DIS_USB_JTAG",                      ESP32C3_EFUSE_DIS_USB_JTAG,                      2,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "DIS_DOWNLOAD_ICACHE",               ESP32C3_EFUSE_DIS_DOWNLOAD_ICACHE,               2,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "DIS_USB_SERIAL_JTAG",               ESP32C3_EFUSE_DIS_USB_SERIAL_JTAG,               2,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "DIS_FORCE_DOWNLOAD",                ESP32C3_EFUSE_DIS_FORCE_DOWNLOAD,                2,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "DIS_TWAI",                          ESP32C3_EFUSE_DIS_TWAI,                          2,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "JTAG_SEL_ENABLE",                   ESP32C3_EFUSE_JTAG_SEL_ENABLE,                   2,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "SOFT_DIS_JTAG",                     ESP32C3_EFUSE_SOFT_DIS_JTAG,                     31,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "DIS_PAD_JTAG",                      ESP32C3_EFUSE_DIS_PAD_JTAG,                      2,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "DIS_DOWNLOAD_MANUAL_ENCRYPT",       ESP32C3_EFUSE_DIS_DOWNLOAD_MANUAL_ENCRYPT,       2,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "USB_EXCHG_PINS",                    ESP32C3_EFUSE_USB_EXCHG_PINS,                    30,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "VDD_SPI_AS_GPIO",                   ESP32C3_EFUSE_VDD_SPI_AS_GPIO,                   30,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "WDT_DELAY_SEL",                     ESP32C3_EFUSE_WDT_DELAY_SEL,                     3,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "SPI_BOOT_CRYPT_CNT",                ESP32C3_EFUSE_SPI_BOOT_CRYPT_CNT,                4,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "SECURE_BOOT_KEY_REVOKE0",           ESP32C3_EFUSE_SECURE_BOOT_KEY_REVOKE0,           5,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "SECURE_BOOT_KEY_REVOKE1",           ESP32C3_EFUSE_SECURE_BOOT_KEY_REVOKE1,           6,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "SECURE_BOOT_KEY_REVOKE2",           ESP32C3_EFUSE_SECURE_BOOT_KEY_REVOKE2,           7,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "KEY_PURPOSE_0",                     ESP32C3_EFUSE_KEY_PURPOSE_0,                     8,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "KEY_PURPOSE_1",                     ESP32C3_EFUSE_KEY_PURPOSE_1,                     9,                         ESP_LOADER_EFUSE_BIT_NONE },
    { "KEY_PURPOSE_2",                     ESP32C3_EFUSE_KEY_PURPOSE_2,                     10,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "KEY_PURPOSE_3",                     ESP32C3_EFUSE_KEY_PURPOSE_3,                     11,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "KEY_PURPOSE_4",                     ESP32C3_EFUSE_KEY_PURPOSE_4,                     12,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "KEY_PURPOSE_5",                     ESP32C3_EFUSE_KEY_PURPOSE_5,                     13,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "SECURE_BOOT_EN",                    ESP32C3_EFUSE_SECURE_BOOT_EN,                    15,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "SECURE_BOOT_AGGRESSIVE_REVOKE",     ESP32C3_EFUSE_SECURE_BOOT_AGGRESSIVE_REVOKE,     16,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "FLASH_TPUW",                        ESP32C3_EFUSE_FLASH_TPUW,                        18,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "DIS_DOWNLOAD_MODE",                 ESP32C3_EFUSE_DIS_DOWNLOAD_MODE,                 18,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "DIS_DIRECT_BOOT",                   ESP32C3_EFUSE_DIS_DIRECT_BOOT,                   18,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "DIS_USB_SERIAL_JTAG_ROM_PRINT",     ESP32C3_EFUSE_DIS_USB_SERIAL_JTAG_ROM_PRINT,     18,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "DIS_USB_SERIAL_JTAG_DOWNLOAD_MODE", ESP32C3_EFUSE_DIS_USB_SERIAL_JTAG_DOWNLOAD_MODE, 18,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "ENABLE_SECURITY_DOWNLOAD",          ESP32C3_EFUSE_ENABLE_SECURITY_DOWNLOAD,          18,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "UART_PRINT_CONTROL",                ESP32C3_EFUSE_UART_PRINT_CONTROL,                18,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "FORCE_SEND_RESUME",                 ESP32C3_EFUSE_FORCE_SEND_RESUME,                 18,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "SECURE_VERSION",                    ESP32C3_EFUSE_SECURE_VERSION,                    18,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "ERR_RST_ENABLE",                    ESP32C3_EFUSE_ERR_RST_ENABLE,                    19,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "DISABLE_WAFER_VERSION_MAJOR",       ESP32C3_EFUSE_DISABLE_WAFER_VERSION_MAJOR,       19,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "DISABLE_BLK_VERSION_MAJOR",         ESP32C3_EFUSE_DISABLE_BLK_VERSION_MAJOR,         19,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "MAC",                               ESP32C3_EFUSE_MAC,                               20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "SPI_PAD_CONFIG_CLK",                ESP32C3_EFUSE_SPI_PAD_CONFIG_CLK,                20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "SPI_PAD_CONFIG_Q",                  ESP32C3_EFUSE_SPI_PAD_CONFIG_Q,                  20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "SPI_PAD_CONFIG_D",                  ESP32C3_EFUSE_SPI_PAD_CONFIG_D,                  20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "SPI_PAD_CONFIG_CS",                 ESP32C3_EFUSE_SPI_PAD_CONFIG_CS,                 20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "SPI_PAD_CONFIG_HD",                 ESP32C3_EFUSE_SPI_PAD_CONFIG_HD,                 20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "SPI_PAD_CONFIG_WP",                 ESP32C3_EFUSE_SPI_PAD_CONFIG_WP,                 20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "SPI_PAD_CONFIG_DQS",                ESP32C3_EFUSE_SPI_PAD_CONFIG_DQS,                20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "SPI_PAD_CONFIG_D4",                 ESP32C3_EFUSE_SPI_PAD_CONFIG_D4,                 20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "SPI_PAD_CONFIG_D5",                 ESP32C3_EFUSE_SPI_PAD_CONFIG_D5,                 20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "SPI_PAD_CONFIG_D6",                 ESP32C3_EFUSE_SPI_PAD_CONFIG_D6,                 20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "SPI_PAD_CONFIG_D7",                 ESP32C3_EFUSE_SPI_PAD_CONFIG_D7,                 20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "WAFER_VERSION_MINOR_LO",            ESP32C3_EFUSE_WAFER_VERSION_MINOR_LO,            20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "PKG_VERSION",                       ESP32C3_EFUSE_PKG_VERSION,                       20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "BLK_VERSION_MINOR",                 ESP32C3_EFUSE_BLK_VERSION_MINOR,                 20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "FLASH_CAP",                         ESP32C3_EFUSE_FLASH_CAP,                         20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "FLASH_TEMP",                        ESP32C3_EFUSE_FLASH_TEMP,                        20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "FLASH_VENDOR",                      ESP32C3_EFUSE_FLASH_VENDOR,                      20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "K_RTC_LDO",                         ESP32C3_EFUSE_K_RTC_LDO,                         20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "K_DIG_LDO",                         ESP32C3_EFUSE_K_DIG_LDO,                         20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "V_RTC_DBIAS20",                     ESP32C3_EFUSE_V_RTC_DBIAS20,                     20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "V_DIG_DBIAS20",                     ESP32C3_EFUSE_V_DIG_DBIAS20,                     20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "DIG_DBIAS_HVT",                     ESP32C3_EFUSE_DIG_DBIAS_HVT,                     20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "THRES_HVT",                         ESP32C3_EFUSE_THRES_HVT,                         20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "WAFER_VERSION_MINOR_HI",            ESP32C3_EFUSE_WAFER_VERSION_MINOR_HI,            20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "WAFER_VERSION_MAJOR",               ESP32C3_EFUSE_WAFER_VERSION_MAJOR,               20,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "OPTIONAL_UNIQUE_ID",                ESP32C3_EFUSE_OPTIONAL_UNIQUE_ID,                21,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "BLK_VERSION_MAJOR",                 ESP32C3_EFUSE_BLK_VERSION_MAJOR,                 21,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "TEMP_CALIB",                        ESP32C3_EFUSE_TEMP_CALIB,                        21,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "OCODE",                             ESP32C3_EFUSE_OCODE,                             21,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "ADC1_INIT_CODE_ATTEN0",             ESP32C3_EFUSE_ADC1_INIT_CODE_ATTEN0,             21,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "ADC1_INIT_CODE_ATTEN1",             ESP32C3_EFUSE_ADC1_INIT_CODE_ATTEN1,             21,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "ADC1_INIT_CODE_ATTEN2",             ESP32C3_EFUSE_ADC1_INIT_CODE_ATTEN2,             21,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "ADC1_INIT_CODE_ATTEN3",             ESP32C3_EFUSE_ADC1_INIT_CODE_ATTEN3,             21,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "ADC1_CAL_VOL_ATTEN0",               ESP32C3_EFUSE_ADC1_CAL_VOL_ATTEN0,               21,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "ADC1_CAL_VOL_ATTEN1",               ESP32C3_EFUSE_ADC1_CAL_VOL_ATTEN1,               21,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "ADC1_CAL_VOL_ATTEN2",               ESP32C3_EFUSE_ADC1_CAL_VOL_ATTEN2,               21,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "ADC1_CAL_VOL_ATTEN3",               ESP32C3_EFUSE_ADC1_CAL_VOL_ATTEN3,               21,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "USER_DATA",                         ESP32C3_EFUSE_USER_DATA,                         22,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "USER_DATA.MAC_CUSTOM",              ESP32C3_EFUSE_USER_DATA_MAC_CUSTOM,              22,                        ESP_LOADER_EFUSE_BIT_NONE },
    { "KEY0",                              ESP32C3_EFUSE_KEY0,                              23,                        32 },
    { "KEY1",                              ESP32C3_EFUSE_KEY1,                              24,                        33 },
    { "KEY2",                              ESP32C3_EFUSE_KEY2,                              25,                        34 },
    { "KEY3",                              ESP32C3_EFUSE_KEY3,                              26,                        35 },
    { "KEY4",                              ESP32C3_EFUSE_KEY4,                              27,                        36 },
    { "KEY5",                              ESP32C3_EFUSE_KEY5,                              28,                        37 },
    { "SYS_DATA_PART2",                    ESP32C3_EFUSE_SYS_DATA_PART2,                    29,                        38 },
};

/* revisions all */
const esp_loader_efuse_field_set_t ESP32C3_EFUSE_FIELDS = {
    .chip = ESP32C3_CHIP, .fields = field_info, .count = sizeof(field_info) / sizeof(field_info[0]),
    .rev_min = 0, .rev_max = ESP_LOADER_CHIP_REV_ANY,
};
