# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
#
# SPDX-License-Identifier: Apache-2.0

# Generated by tools/copy_efuse_headers.py -- do not edit.
#
# The per-chip field tables, listed rather than globbed. A glob would either go
# stale until the next manual re-configure, or need CONFIGURE_DEPENDS, which
# CMake rejects in the script mode ESP-IDF uses to collect component
# requirements. Regenerating the tables rewrites this list, so it cannot drift.
#
# Only sets a variable: what to do with it is the includer's business, and
# CMAKE_CURRENT_LIST_DIR keeps the paths correct wherever it is included from.
set(EFUSE_TABLE_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/esp32/esp_loader_efuse_table.c
    ${CMAKE_CURRENT_LIST_DIR}/esp32c2/esp_loader_efuse_table.c
    ${CMAKE_CURRENT_LIST_DIR}/esp32c3/esp_loader_efuse_table.c
    ${CMAKE_CURRENT_LIST_DIR}/esp32c5/esp_loader_efuse_table.c
    ${CMAKE_CURRENT_LIST_DIR}/esp32c6/esp_loader_efuse_table.c
    ${CMAKE_CURRENT_LIST_DIR}/esp32c61/esp_loader_efuse_table.c
    ${CMAKE_CURRENT_LIST_DIR}/esp32h2/esp_loader_efuse_table.c
    ${CMAKE_CURRENT_LIST_DIR}/esp32h2/esp_loader_efuse_table_v0.0_v1.1.c
    ${CMAKE_CURRENT_LIST_DIR}/esp32p4/esp_loader_efuse_table.c
    ${CMAKE_CURRENT_LIST_DIR}/esp32p4/esp_loader_efuse_table_rev1.c
    ${CMAKE_CURRENT_LIST_DIR}/esp32s2/esp_loader_efuse_table.c
    ${CMAKE_CURRENT_LIST_DIR}/esp32s3/esp_loader_efuse_table.c
)
