/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Generated by tools/copy_efuse_headers.py. Resolves a chip and its revision to
 * the field metadata that describes it.
 *
 * Its own translation unit on purpose: it names every chip's field set, so
 * linking it pulls them all in. Kept apart, an application that never calls
 * esp_loader_efuse_get_field_info() never pulls this object out of the archive
 * and pays nothing for the tables -- with or without --gc-sections.
 */

#include "esp_loader_efuse.h"

#include "efuse/esp32/esp_loader_efuse_table.h"
#include "efuse/esp32c2/esp_loader_efuse_table.h"
#include "efuse/esp32c3/esp_loader_efuse_table.h"
#include "efuse/esp32c5/esp_loader_efuse_table.h"
#include "efuse/esp32c6/esp_loader_efuse_table.h"
#include "efuse/esp32c61/esp_loader_efuse_table.h"
#include "efuse/esp32h2/esp_loader_efuse_table.h"
#include "efuse/esp32p4/esp_loader_efuse_table.h"
#include "efuse/esp32s2/esp_loader_efuse_table.h"
#include "efuse/esp32s3/esp_loader_efuse_table.h"

/* Ordered: a set with a narrow revision range precedes the catch-all for the
 * same chip, and the first match wins. */
static const esp_loader_efuse_field_set_t *const field_sets[] = {
    &ESP32_EFUSE_FIELDS,
    &ESP32C2_EFUSE_FIELDS,
    &ESP32C3_EFUSE_FIELDS,
    &ESP32C5_EFUSE_FIELDS,
    &ESP32C6_EFUSE_FIELDS,
    &ESP32C61_EFUSE_FIELDS,
    &ESP32H2_V0_0_V1_1_EFUSE_FIELDS,
    &ESP32H2_EFUSE_FIELDS,
    &ESP32P4_EFUSE_FIELDS,
    &ESP32P4_REV1_EFUSE_FIELDS,
    &ESP32S2_EFUSE_FIELDS,
    &ESP32S3_EFUSE_FIELDS,
};

esp_loader_error_t esp_loader_efuse_get_field_info(
    target_chip_t chip,
    uint16_t revision,
    const esp_loader_efuse_field_set_t **set)
{
    for (size_t i = 0; i < sizeof(field_sets) / sizeof(field_sets[0]); i++) {
        const esp_loader_efuse_field_set_t *candidate = field_sets[i];

        if (candidate->chip == chip &&
            revision >= candidate->rev_min && revision <= candidate->rev_max) {
            *set = candidate;
            return ESP_LOADER_SUCCESS;
        }
    }

    return ESP_LOADER_ERROR_UNSUPPORTED_CHIP;
}
