name: Pre-commit checks

on: pull_request

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --show-diff-on-failure --from-ref origin/master --to-ref HEAD
